### ISSUE TITLE
Watch-list Issue: Not Displaying in Correct Format

### ISSUE THREAD

**Issue by Botond72** [cian74/Mobile60Project#1]
@cian74 
#watchlist
Doesn't save watch-listed movies in correct format

**Comment by cian74** [comment]
![buggedWatchlist](https://github.com/cian74/Mobile60Project/assets/131063119/aa62f90c-2dcd-43e2-8fbb-8d7b36791bf0)

bugged watchlist which had stored data from testing. Presuming from the results Array as it had 20 stored movies.


![fixWatchlist](https://github.com/cian74/Mobile60Project/assets/131063119/8b0b33cc-45ad-4307-a79a-b7d2059b6d50)

fixed watch
